server:
  port: 8080
spring:
  datasource:
    url: ${env.PROD_DB_URL:jdbc:postgresql://localhost:5432/productdb}
    username: ${env.PROD_DB_USER:produser}
    password: ${env.PROD_DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          nbpratesclient:
            url: https://api.nbp.pl

logging:
  level:
    root: DEBUG
